language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install pep8
  - python setup.py install

script:
  - cd tests
  - python run_tests.py
  - cd ..
  - find . -type f -name "*.py" | xargs pep8
